databaseChangeLog:
  - changeSet:
      id: 1
      author: jude
      changes:
        - createTable:
            tableName: configuration
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: total_tickets
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: ticket_release_rate
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: customer_retrieval_rate
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: maximum_ticket_capacity
                  type: int
                  constraints:
                    nullable: false
